accounts:
    - name: seller
      coins: ["20000token", "200000000stake"]
    - name: buyer1
      coins: ["10000token", "100000000stake"]
    - name: buyer2
      coins: ["10000token", "100000000stake"]
    - name: buyer3
      coins: ["10000token", "100000000stake"]
validator:
    name: seller
    staked: "100000000stake"
client:
    openapi:
        path: "docs/static/openapi.yml"
faucet:
    name: buyer1
    coins: ["5token", "100000stake"]
