accounts:
    - name: landlord
      coins: ["20000token", "200000000stake"]
    - name: tenant1
      coins: ["11token", "100000000stake"]
    - name: tenant2
      coins: ["10000token", "100000000stake"]
    - name: tenant3
      coins: ["10000token", "100000000stake"]
validator:
    name: landlord
    staked: "100000000stake"
client:
    openapi:
        path: "docs/static/openapi.yml"
    vuex:
        path: "vue/src/store"
faucet:
    name: tenant1
    coins: ["5token", "100000stake"]
